import type { XtermTheme } from './types'

export const OMT_DARK: XtermTheme = {
  name: 'OpenMultiTerm Dark',
  variant: 'dark',
  fontFamily: '"Consolas", "Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Cascadia Code", monospace',
  background: '#0a0a14',
  foreground: '#e0e0e8',
  cursor: '#7c5cfc',
  cursorAccent: '#0a0a14',
  selectionBackground: '#7c5cfc44',
  black: '#1a1a2e',
  brightBlack: '#2a2a48',
  red: '#ff5252',
  brightRed: '#ff6e6e',
  green: '#00e676',
  brightGreen: '#69f0ae',
  yellow: '#ffd740',
  brightYellow: '#ffe57f',
  blue: '#448aff',
  brightBlue: '#82b1ff',
  magenta: '#e040fb',
  brightMagenta: '#f48fb1',
  cyan: '#18ffff',
  brightCyan: '#84ffff',
  white: '#e0e0e8',
  brightWhite: '#ffffff',
}

export const OMT_LIGHT: XtermTheme = {
  name: 'OpenMultiTerm Light',
  variant: 'light',
  fontFamily: '"Consolas", "Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Cascadia Code", monospace',
  background: '#f5f5fa',
  foreground: '#1a1a2e',
  cursor: '#7c5cfc',
  cursorAccent: '#ffffff',
  selectionBackground: '#7c5cfc22',
  black: '#e8e8f0',
  brightBlack: '#d0d0e0',
  red: '#d32f2f',
  brightRed: '#f44336',
  green: '#2e7d32',
  brightGreen: '#4caf50',
  yellow: '#f57f17',
  brightYellow: '#ffb300',
  blue: '#1565c0',
  brightBlue: '#42a5f5',
  magenta: '#7b1fa2',
  brightMagenta: '#ab47bc',
  cyan: '#00838f',
  brightCyan: '#26c6da',
  white: '#1a1a2e',
  brightWhite: '#0a0a14',
}

export const ONE_DARK: XtermTheme = {
  name: 'One Dark',
  variant: 'dark',
  fontFamily: '"Consolas", "Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Fira Code", monospace',
  background: '#282c34',
  foreground: '#abb2bf',
  cursor: '#528bff',
  cursorAccent: '#282c34',
  selectionBackground: '#3e4451',
  black: '#282c34',
  brightBlack: '#5c6370',
  red: '#e06c75',
  brightRed: '#be5046',
  green: '#98c379',
  brightGreen: '#7ec87c',
  yellow: '#e5c07b',
  brightYellow: '#d19a66',
  blue: '#61afef',
  brightBlue: '#528bff',
  magenta: '#c678dd',
  brightMagenta: '#a96cd5',
  cyan: '#56b6c2',
  brightCyan: '#56b6c2',
  white: '#abb2bf',
  brightWhite: '#ffffff',
}

export const DRACULA: XtermTheme = {
  name: 'Dracula',
  variant: 'dark',
  fontFamily: '"Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Fira Code", "Cascadia Code", monospace',
  background: '#282a36',
  foreground: '#f8f8f2',
  cursor: '#f8f8f2',
  cursorAccent: '#282a36',
  selectionBackground: '#44475a',
  black: '#21222c',
  brightBlack: '#6272a4',
  red: '#ff5555',
  brightRed: '#ff6e6e',
  green: '#50fa7b',
  brightGreen: '#69ff94',
  yellow: '#f1fa8c',
  brightYellow: '#ffffa5',
  blue: '#bd93f9',
  brightBlue: '#d6acff',
  magenta: '#ff79c6',
  brightMagenta: '#ff92df',
  cyan: '#8be9fd',
  brightCyan: '#a4ffff',
  white: '#f8f8f2',
  brightWhite: '#ffffff',
}

export const TOKYO_NIGHT: XtermTheme = {
  name: 'Tokyo Night',
  variant: 'dark',
  fontFamily: '"Consolas", "Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Cascadia Code", monospace',
  background: '#1a1b26',
  foreground: '#c0caf5',
  cursor: '#c0caf5',
  cursorAccent: '#1a1b26',
  selectionBackground: '#283457',
  black: '#15161e',
  brightBlack: '#414868',
  red: '#f7768e',
  brightRed: '#f7768e',
  green: '#9ece6a',
  brightGreen: '#9ece6a',
  yellow: '#e0af68',
  brightYellow: '#e0af68',
  blue: '#7aa2f7',
  brightBlue: '#7aa2f7',
  magenta: '#bb9af7',
  brightMagenta: '#bb9af7',
  cyan: '#7dcfff',
  brightCyan: '#7dcfff',
  white: '#c0caf5',
  brightWhite: '#c0caf5',
}

export const NORD: XtermTheme = {
  name: 'Nord',
  variant: 'dark',
  fontFamily: '"Consolas", "Noto Sans Mono", "JetBrains Mono", "JetBrainsMono Nerd Font", "Cascadia Mono", monospace',
  background: '#2e3440',
  foreground: '#d8dee9',
  cursor: '#d8dee9',
  cursorAccent: '#2e3440',
  selectionBackground: '#434c5e',
  black: '#3b4252',
  brightBlack: '#4c566a',
  red: '#bf616a',
  brightRed: '#bf616a',
  green: '#a3be8c',
  brightGreen: '#a3be8c',
  yellow: '#ebcb8b',
  brightYellow: '#ebcb8b',
  blue: '#81a1c1',
  brightBlue: '#81a1c1',
  magenta: '#b48ead',
  brightMagenta: '#b48ead',
  cyan: '#88c0d0',
  brightCyan: '#8fbcbb',
  white: '#e5e9f0',
  brightWhite: '#eceff4',
}

export const ALL_THEMES: XtermTheme[] = [
  OMT_DARK,
  OMT_LIGHT,
  ONE_DARK,
  DRACULA,
  TOKYO_NIGHT,
  NORD,
]

export const DARK_THEMES: XtermTheme[] = ALL_THEMES.filter((t) => t.variant === 'dark')
export const LIGHT_THEMES: XtermTheme[] = ALL_THEMES.filter((t) => t.variant === 'light')
